# Generated by Django 3.1.6 on 2021-02-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile',
        ),
    ]
