# Generated by Django 3.1.6 on 2021-02-09 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import media_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrName', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('userPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgs', models.ImageField(blank=True, null=True, upload_to=media_api.models.upload_post_path)),
                ('imgPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_api.imagepost')),
                ('userImg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userImg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
